//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsUtilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JSResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JSResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebFormsUtilities.JSResources", typeof(JSResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot; language=&quot;javascript&quot;&gt;
        /////WFUtilitiesJquery.js
        ///// This script uses jQuery for validation instead of Microsoft&apos;s AJAX libraries.
        ///// If jQuery is being used it will reduce the JS footprint.
        ///
        ///// WFUtilities
        ///function WFSubmitForm(methodName) {
        ///    var elem = $(&apos;#JSMethod&apos;);
        ///    var elemStr = &apos;&lt;input type=&quot;hidden&quot; name=&quot;JSMethod&quot; id=&quot;JSMethod&quot; value=&quot;&apos; + methodName + &apos;&quot; /&gt;&apos;;
        ///    if (elem[0] === undefined) {
        ///        elem = $(&apos;#Form1&apos;).append(elemStr); //.net 4
        ///        elem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WFUtilitiesJquery {
            get {
                return ResourceManager.GetString("WFUtilitiesJquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script language=&quot;javascript&quot; type=&quot;text/javascript&quot;&gt;function WFSubmitForm(a){var b=$(&quot;#JSMethod&quot;),a=&apos;&lt;input type=&quot;hidden&quot; name=&quot;JSMethod&quot; id=&quot;JSMethod&quot; value=&quot;&apos;+a+&apos;&quot; /&gt;&apos;;b[0]===void 0?($(&quot;#Form1&quot;).append(a),$(&quot;#form1&quot;).append(a)):$(&quot;#JSMethod&quot;).replaceWith(a);(document.forms.Form1||document.forms.form1).submit();return!1}
        ///function WFCallPage(a,b){if(b.data===void 0||b.data===null||b.data===&quot;&quot;)b.data=&quot;{}&quot;;$.ajax({type:&quot;POST&quot;,url:a,data:b.data,contentType:&quot;application/json; charset=utf-8&quot;,dataType:&quot;json&quot;,su [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WFUtilitiesJqueryMin {
            get {
                return ResourceManager.GetString("WFUtilitiesJqueryMin", resourceCulture);
            }
        }
    }
}
