//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsUtilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JSResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JSResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebFormsUtilities.JSResources", typeof(JSResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&quot;jquery-1.5.1.js&quot; /&gt;
        ///
        ////*!
        ///** Unobtrusive Ajax support library for jQuery
        ///** Copyright (C) Microsoft Corporation. All rights reserved.
        ///*/
        ///
        ////*jslint white: true, browser: true, onevar: true, undef: true, nomen: true, eqeqeq: true, plusplus: true, bitwise: true, regexp: true, newcap: true, immed: true, strict: false */
        ////*global window: false, jQuery: false */
        ///
        ///(function($) {
        ///    var data_click = &quot;unobtrusiveAjaxClick&quot;,
        ///        data_validation = &quot;unobtrusiveValidation&quot;;
        ///
        ///    fu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jqueryUnobtrusiveAjax {
            get {
                return ResourceManager.GetString("jqueryUnobtrusiveAjax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&quot;jquery-1.5.1.js&quot; /&gt;
        ////// &lt;reference path=&quot;jquery.validate.js&quot; /&gt;
        ///
        ////*!
        ///** Unobtrusive validation support library for jQuery and jQuery Validate
        ///** Copyright (C) Microsoft Corporation. All rights reserved.
        ///*/
        ///
        ////*jslint white: true, browser: true, onevar: true, undef: true, nomen: true, eqeqeq: true, plusplus: true, bitwise: true, regexp: true, newcap: true, immed: true, strict: false */
        ////*global document: false, jQuery: false */
        ///
        ///(function($) {
        ///    var $jQval = $.validator,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jqueryValidateUnobtrusive {
            get {
                return ResourceManager.GetString("jqueryValidateUnobtrusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // register custom jQuery methods
        ///if (jQuery.validator) { //Only if validator plugin is loaded
        ///    jQuery.validator.addMethod(&quot;regex&quot;, function(value, element, params) {
        ///        if (this.optional(element)) {
        ///            return true;
        ///        }
        ///
        ///        var match = new RegExp(params).exec(value);
        ///        return (match &amp;&amp; (match.index == 0) &amp;&amp; (match[0].length == value.length));
        ///    });
        ///}
        ///
        /////Most of these methods are &quot;ripped-off&quot; from Microsoft&apos;s MVC validation JavaScript and changed slightly.
        ///fun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SetupClientValidation {
            get {
                return ResourceManager.GetString("SetupClientValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //WFUtilitiesJquery.js
        ///(function(context) {
        ///    var $wf = function() {
        ///        /// &lt;summary&gt;
        ///        /// WebFu JavaScript object. Can be accessed via $wf or webfu.
        ///        ///&amp;#10; Functions include:
        ///        ///&amp;#10; webfu.submitForm()
        ///        ///&amp;#10; webfu.enableUpload()
        ///        ///&amp;#10; webfu.callPage()
        ///        ///&amp;#10; webfu.serializePage()
        ///        return new $wf.fn.init(context);
        ///    };
        ///    //Would like to imitate jQuery here somewhat
        ///    //$wf.fn = { &quot;webfu&quot;: &apos;0.2012.03.28&apos; };
        ///    //$wf. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WFUtilitiesJquery {
            get {
                return ResourceManager.GetString("WFUtilitiesJquery", resourceCulture);
            }
        }
    }
}
